all: frequencies huffman encode decode

frequencies: Frequencies.cpp
	g++ -o frequencies Frequencies.cpp

huffman: Huffman.cpp
	g++ -o huffman Huffman.cpp
	
encode: Encode.cpp
	g++ -o encode Encode.cpp

decode: Decode.cpp
	g++ -o decode Decode.cpp